version: "3.3"

services:
  quay-service-tool-api:
    container_name: "quay-service-tool-api"
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development

  quay-service-tool-client:
    container_name: "quay-service-tool-client"
    build: ./frontend
    volumes:
      - './frontend:/usr/src/app'
    ports:
      - '9000:9000'
    depends_on:
      - quay-service-tool-api
    environment:
      - NODE_ENV=development
